---
- hosts: workstations
  become: true
  tasks:
    - name: Auto start Apache server on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"

