---
- hosts: all
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install apache2 and php packages
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest

