---
- name: Install Nginx on Ubuntu
  hosts: workstations
  become: true
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

