---
- hosts: web_servers
  become: true
  tasks:
    - name: copy default html files for site
      tags: apache2
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

