---
- name: Install Grafana
  hosts: your_grafana_host
  become: yes
  vars:
    ansible_ssh_private_key_file: /path/to/your/private/key.pem
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Grafana dependencies
      apt:
        name:
          - software-properties-common
          - add-apt-repository
      become: yes

    - name: Add Grafana APT repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
      become: yes

    - name: Import Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
      become: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present
      become: yes

    - name: Start Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes

