---
- name: Ensure required packages are installed for workstations
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - htop

- name: Configure timezone for workstations
  timezone:
    name: "America/New_York"
  notify: Restart services

