---
- name: Get EC2 Instance Status
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Query AWS for EC2 instance status
      community.aws.ec2_instance_info:
        instance_ids:
          - i-00093f4f7132a6449  # Replace with your instance ID
        region: us-east-1  # Replace with your AWS region
      register: ec2_instance_info

    - name: Display EC2 instance status
      debug:
        var: ec2_instance_info.instances[0].state.name

