---
- name: Reboot Multiple EC2 Instances
  hosts: localhost
  vars:
    region: "us-east-1"
    instance_ids:
      - "i-00093f4f7132a6449"
      - "i-0c0a8580a03bf315f"

  tasks:
    - name: Reboot the specified EC2 instances asynchronously
      community.aws.ec2_instance:
        instance_ids: "{{ instance_ids }}"
        region: "{{ region }}"
        state: restarted
        wait: no
      async: 120
      poll: 0
      register: reboot_results

