- name: Reboot EC2 Instance
  hosts: localhost
  vars:
    region: "us-east-1"  # Update with your region
    instance_id: "i-0b231d9b13ea70f14"  # Update with your instance ID

  tasks:
    - name: Stop the specified EC2 instance
      community.aws.ec2_instance:
        region: "{{ region }}"
        instance_ids: "{{ instance_id }}"
        state: stopped
      register: stop_result

    - name: Wait for the instance to be in "stopped" state
      wait_for:
        timeout: 180  # 3 minutes
        delay: 10  # Check every 10 seconds
        host: "{{ instance_id }}"
        port: 22
        state: stopped
      when: stop_result.changed

    - name: Reboot the specified EC2 instance
      community.aws.ec2_instance:
        region: "{{ region }}"
        instance_ids: "{{ instance_id }}"
        state: restarted
      register: reboot_result

    - name: Wait for the instance to be in "running" state
      wait_for:
        timeout: 180  # 3 minutes
        delay: 10  # Check every 10 seconds
        host: "{{ instance_id }}"
        port: 22
        state: started
      when: reboot_result.changed

    - name: Print a message indicating the reboot
      debug:
        msg: "The EC2 instance with ID {{ instance_id }} has been successfully rebooted."
      when: reboot_result.changed

