- name: Stop Multiple EC2 Instances
  hosts: localhost
  vars:
    region: "us-east-1"  # Update with your region
    instance_ids:
      - "i-00093f4f7132a6449"  # Update with your instance IDs
      - "i-0c0a8580a03bf315f"  # Add more instance IDs as needed
      - "i-022c398fdd918afa7"
      - "i-0b231d9b13ea70f14"
      - "i-0bed6f40bf1174ac0"
  tasks:
    - name: Get information about the specified EC2 instances
      community.aws.ec2_instance_info:
        region: "{{ region }}"
        instance_ids: "{{ instance_ids }}"
      register: ec2_instance_info

    - name: Check if any instances are not running
      fail:
        msg: "One or more specified EC2 instances are not in the 'running' state."
      when: item.state.name != 'running'
      loop: "{{ ec2_instance_info.instances }}"

    - name: Stop the EC2 instances
      community.aws.ec2_instance:
        region: "{{ region }}"
        instance_ids: "{{ instance_ids }}"
        state: stopped
      when: ec2_instance_info.instances | length > 0  # Only stop instances if there are running instances

