- name: Terminate Multiple EC2 Instances
  hosts: localhost
  vars:
    region: "ca-central-1"  # Update with your region
    instance_ids:
      - "i-0c6c897d364139e1e"
      - "i-080ae62da720e0eb2"
      - "i-0166d4c4465fecc3e"
      - "i-06b61d5e826db3e94"

  tasks:
    - name: Terminate the specified EC2 instances
      community.aws.ec2_instance:
        region: "{{ region }}"
        instance_ids: "{{ instance_ids }}"
        state: absent

