---
- name: Upload file to S3 bucket
  hosts: localhost
  connection: local
  vars_files:
    - creds.yml

  tasks:
    - name: Upload files to S3 bucket
      community.aws.s3_sync:
        bucket: testansiblebucket-s3  # Replace with your actual S3 bucket name
        file_root: /home/daniel/Ansible/AWS/S3/  # Replace with the local directory containing files
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"

