---
- name: Manage S3 Bucket Notifications
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Configure S3 Bucket Notification
      community.aws.s3_bucket_notification:
        name: my-ansible-s3-bucket
        lambda_function_arn: arn:aws:lambda:us-east-1:123456789012:function:my-lambda-function
        event: s3:ObjectCreated:*
        state: present
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"

