---
- name: Install Terraform on Ubuntu
  hosts: workstations
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install unzip and wget
      apt:
        name:
          - unzip
          - wget

    - name: Download Terraform
      unarchive:
        src: "https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip"  # Corrected the URL
        dest: "/usr/local/bin"
        remote_src: yes
        mode: '0755'
        owner: root

